### ISSUE TITLE
White text on non-sortable columns headers

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/encore-ui#1491] opened 2016-01-11 22:09 UTC
I just noticed that non-sortable headers are white. Was this an oversight or Purpose ? 

<img width="708" alt="screen shot 2016-01-11 at 4 05 06 pm" src="https://cloud.githubusercontent.com/assets/5339195/12248177/47245806-b87d-11e5-81f5-e8f6941292cb.png">
This screen shot was taken from the Cloud Servers table in `encore-cloud-ui`.

**Comment by cgtaab** [comment] 2016-01-11 22:22
Seems like an oversight to me.

**Comment by ErnieAtLYD** [comment] 2016-01-11 22:31
Hey there - thanks for dropping a line. What part of Encore are you seeing this on (urls, etc)?

**Comment by glynnis** [comment] 2016-01-11 22:34
Hey @ErnieAtLYD @cgtaab --

@jonkruse00 and I just discussed this on Slack and got to the bottom of it:

The current styles in the Framework for Tables (http://rackerlabs.github.io/encore-ui/#/molecules/tables) and sortable columns (http://rackerlabs.github.io/encore-ui/#/components/rxSortableColumn) indicate that this isn’t a Framework issue. 

The problem is with some custom CSS in the project (not the Framework), and the use of a class defined in the project, `.column-title` and the styles defined here: https://github.com/rackerlabs/encore-cloud-ui/blob/1d42cf4f758ebb3402c7a99af4f2f20385500c46/app/styles/servers.less#L38

@jonkruse00 and @cgtaab will be following up with their team to get this into the backlog.

Since this isn't a Framework problem, I'm closing this issue.

**Closed by glynnis** 2016-01-11 22:34 UTC
