### ISSUE TITLE
Notifications Hiding Data

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#995] opened 2015-05-27 21:40 UTC
JIRA [FRMW-136](https://jira.rax.io/browse/FRMW-136)

*Breadcrumbs and account banner is hidden from view until user manually dismisses notifications.*
![cloud servers](https://cloud.githubusercontent.com/assets/545605/7848028/d1c3f808-048d-11e5-997b-4476fd081b0a.png)

In addition to being an annoyance for users, there have also been concerns that this is causing headaches with front-end tests.

**Comment by glynnis** [comment] 2015-05-27 21:44
For some additional context (don't know if this is helpful or not): the floating notifications were created as a solution for another problem that was annoying to users: notifications used to appear at the top of all content and push content down/up as the notifications appeared and disappeared. I mention it only to expose the fact that switching back to a "put it at the top, push down content" design will not be acceptable, and we'll have to come up with something different that addresses both issues: not pushing content down, and not covering content up.

**Comment by CITguy** [comment] 2015-05-27 23:19
@glynnis, you are correct. I forgot to tag this as "Needs Design", but you beat me to it.

**Comment by glynnis** [comment] 2015-10-29 21:04
This is being looked at by designers currently, and has been captured on the UX Board here: https://jira.rax.io/browse/UXENCORE-400. Closing this.

**Closed by glynnis** 2015-10-29 21:04 UTC
Labels: Needs Design
